version: '3.8'
services:
  onlyoffice-document-server:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-document-server
    restart: unless-stopped
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: "supersecretkey123456"
    volumes:
      - onlyoffice-data:/var/www/onlyoffice/Data
      - onlyoffice-log:/var/log/onlyoffice
      - onlyoffice-lib:/var/lib/onlyoffice

volumes:
  onlyoffice-data:
  onlyoffice-log:
  onlyoffice-lib:
