"""add dao and related tables

Revision ID: 0001_add_dao_tables
Revises: 
Create Date: 2025-09-01 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_add_dao_tables'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - add dao core tables ###
    op.create_table(
        'dao',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('document_id', sa.Integer(), nullable=True),
        sa.Column('reference', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    )

    op.create_table(
        'dao_lots',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('id_dao', sa.Integer(), sa.ForeignKey('dao.id', ondelete='CASCADE'), nullable=False),
        sa.Column('lot_name', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    )

    op.create_table(
        'dao_price_mo',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('id_lot', sa.Integer(), sa.ForeignKey('dao_lots.id', ondelete='CASCADE'), nullable=False),
        sa.Column('poste', sa.String(length=255), nullable=False),
        sa.Column('horaire_mensuel', sa.Numeric(19,2), nullable=True),
        sa.Column('charges', sa.Numeric(19,2), nullable=True),
        sa.Column('temps', sa.Numeric(19,2), nullable=True),
        sa.Column('salaire_horaire', sa.Numeric(19,2), nullable=True),
        sa.Column('total', sa.Numeric(19,2), nullable=True),
    )

    op.create_table(
        'dao_price_mtx',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('id_lot', sa.Integer(), sa.ForeignKey('dao_lots.id', ondelete='CASCADE'), nullable=False),
        sa.Column('designation', sa.String(length=255), nullable=False),
        sa.Column('quantite', sa.Numeric(19,2), nullable=True),
        sa.Column('prix_unitaire', sa.Numeric(19,2), nullable=True),
        sa.Column('total', sa.Numeric(19,2), nullable=True),
    )

    op.create_table(
        'dao_price_equ',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('id_lot', sa.Integer(), sa.ForeignKey('dao_lots.id', ondelete='CASCADE'), nullable=False),
        sa.Column('designation', sa.String(length=255), nullable=False),
        sa.Column('quantite', sa.Numeric(19,2), nullable=True),
        sa.Column('prix_unitaire', sa.Numeric(19,2), nullable=True),
        sa.Column('total', sa.Numeric(19,2), nullable=True),
    )

    op.create_table(
        'dao_price_sdp',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('id_lot', sa.Integer(), sa.ForeignKey('dao_lots.id', ondelete='CASCADE'), nullable=False),
        sa.Column('description', sa.String(length=512), nullable=True),
        sa.Column('quantite', sa.Numeric(19,2), nullable=True),
        sa.Column('prix_unitaire', sa.Numeric(19,2), nullable=True),
        sa.Column('total', sa.Numeric(19,2), nullable=True),
    )

    op.create_table(
        'dao_price_sdp_posts',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('id_sdp', sa.Integer(), sa.ForeignKey('dao_price_sdp.id', ondelete='CASCADE'), nullable=False),
        sa.Column('titre', sa.String(length=255), nullable=False),
        sa.Column('ordre', sa.Integer(), nullable=True),
    )

    op.create_table(
        'dao_price_sdp_articles',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('id_post', sa.Integer(), sa.ForeignKey('dao_price_sdp_posts.id', ondelete='CASCADE'), nullable=False),
        sa.Column('designation', sa.String(length=512), nullable=False),
        sa.Column('quantite', sa.Numeric(19,2), nullable=True),
        sa.Column('prix_unitaire', sa.Numeric(19,2), nullable=True),
        sa.Column('total', sa.Numeric(19,2), nullable=True),
    )

    op.create_table(
        'dao_price_bde',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('id_lot', sa.Integer(), sa.ForeignKey('dao_lots.id', ondelete='CASCADE'), nullable=False),
        sa.Column('poste', sa.String(length=255), nullable=True),
        sa.Column('quantite', sa.Numeric(19,2), nullable=True),
        sa.Column('prix_unitaire', sa.Numeric(19,2), nullable=True),
        sa.Column('total', sa.Numeric(19,2), nullable=True),
    )

    op.create_table(
        'dao_tasks',
        sa.Column('id', sa.String(length=64), primary_key=True),
        sa.Column('titre', sa.String(length=255), nullable=False),
        sa.Column('ordre', sa.Integer(), nullable=True),
        sa.Column('id_lot', sa.Integer(), sa.ForeignKey('dao_lots.id', ondelete='CASCADE'), nullable=False),
    )

    op.create_table(
        'dao_subtasks',
        sa.Column('id', sa.String(length=64), primary_key=True),
        sa.Column('titre', sa.String(length=255), nullable=False),
        sa.Column('done', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('ordre', sa.Integer(), nullable=True),
        sa.Column('content_markdown', sa.Text(), nullable=True),
        sa.Column('id_task', sa.String(length=64), sa.ForeignKey('dao_tasks.id', ondelete='CASCADE'), nullable=False),
    )

    # add indexes for quick lookup
    op.create_index('ix_dao_reference', 'dao', ['reference'], unique=False)
    op.create_index('ix_dao_lots_lot_name', 'dao_lots', ['lot_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - drop tables in reverse order ###
    op.drop_index('ix_dao_lots_lot_name', table_name='dao_lots')
    op.drop_index('ix_dao_reference', table_name='dao')

    op.drop_table('dao_subtasks')
    op.drop_table('dao_tasks')
    op.drop_table('dao_price_bde')
    op.drop_table('dao_price_sdp_articles')
    op.drop_table('dao_price_sdp_posts')
    op.drop_table('dao_price_sdp')
    op.drop_table('dao_price_equ')
    op.drop_table('dao_price_mtx')
    op.drop_table('dao_price_mo')
    op.drop_table('dao_lots')
    op.drop_table('dao')
    # ### end Alembic commands ###
